### ISSUE TITLE
Update link to point to kohanaframework, not kohanaphp

### ISSUE THREAD

**Issue by randomecho** [kohana/userguide#75]
The link on the GitHub description header still points to the now dead kohanaphp.com URL where it should be pointing to kohanaframework.org 

Or http://kohanaframework.org/documentation to go right to it.

**Comment by lenton** [comment]
Thank you for bringing this to our attention.

The repository kohana/database also has the old website URL in its description.

**Comment by shadowhand** [comment]
Fixed!

**Comment by lenton** [comment]
@shadowhand You missed the kohana/database's description.

**Comment by shadowhand** [comment]
@lenton d'oh that's what I get for reading too fast. Fixed!
